# ------------------------------------------------------------------------------------------------ #
#                                CosmoScout VR Monitor Slave                                      #
# ------------------------------------------------------------------------------------------------ #

[SYSTEM]
DISPLAYSYSTEMS   = MAIN
WINDOWINGTOOLKIT = SDL2
INTERACTIONINI	 = interaction_hmd.ini
GRAPHICSSECTION  = GRAPHICS
OUTPUT           = OUTPUT

[GRAPHICS]
BACKGROUNDCOLOR  = 0.0, 0.0, 0.0


############################ windows ##################################

[MONITOR_WINDOW]
NAME                = MONITOR_WINDOW
STEREO              = false
POSITION            = 100, 100
SIZE                = 1280, 800
FULLSCREEN          = false
TITLE               = CosmoScout Screen
VSYNC               = false
MULTISAMPLES        = 0


######################## display systems ##############################

[FRAME_MONITOR]
TRANSLATION         = 0, 0, 0

[MAIN]
NAME                = MAIN
VIEWPORTS           = MONITOR_VIEWPORT
REFERENCE_FRAME     = FRAME_MONITOR
LEFT_EYE_OFFSET     = -0.03, 0, 0
RIGHT_EYE_OFFSET    = 0.03, 0, 0

[MONITOR_VIEWPORT]
NAME                = MONITOR_VIEWPORT
PROJECTION          = PROJECTION_MONO
WINDOW              = MONITOR_WINDOW
RESIZE_WITH_WINDOW  = true

[PROJECTION_MONO]
NAME                = PROJECTION_MONO
PROJ_PLANE_MIDPOINT = 0, 0, -7.0
PROJ_PLANE_EXTENTS  = -5.333, 5.333, -3.0, 3.0
CLIPPING_RANGE      = 0.5, 5000
STEREO_MODE         = MONO


########################## cluster ################################

[MONITOR]
NAME                = MONITOR
DISPLAYSYSTEMS      = MAIN
WINDOWINGTOOLKIT    = SDL2
SLAVEIP             = 127.0.0.1
SLAVEPORT           = 50000